"""
mappings.py — Canonical Registry (Tier 1 lookup tables)
Covers all test names and units seen in typical Indian hospital lab reports.
"""

# ─── TEST NAME CANONICAL REGISTRY ─────────────────────────────────────────────
# Keys  : raw strings (UPPERCASE) found in lab reports
# Values: canonical standardized name used in output schema

TEST_MAPPING: dict[str, str] = {
    # ── Haemoglobin ──
    "HAEMOGLOBIN":                           "HAEMOGLOBIN",
    "HEMOGLOBIN":                            "HAEMOGLOBIN",
    "HAEMOGLOBIN (HB)":                      "HAEMOGLOBIN",
    "HEMOGLOBIN (HB)":                       "HAEMOGLOBIN",
    "HB":                                    "HAEMOGLOBIN",
    "HGB":                                   "HAEMOGLOBIN",
    "AEMOGLOBIN":                            "HAEMOGLOBIN",
    "HB%":                                   "HAEMOGLOBIN",
    "HAEMOGLOBIN%":                          "HAEMOGLOBIN",
    "HEMOGLOBIN LEVEL":                      "HAEMOGLOBIN",

    # ── WBC ──
    "WHITE BLOOD CELL COUNT":                "WBC",
    "WBC":                                   "WBC",
    "TOTAL WBC COUNT":                       "WBC",
    "LEUKOCYTE COUNT":                       "WBC",
    "TLC":                                   "WBC",
    "TOTAL LEUCOCYTE COUNT":                 "WBC",
    "TOTAL LEUCOCYTE COUNT (TLC)":           "WBC",
    "TOTAL WBC":                             "WBC",
    "LEUCOCYTE COUNT":                       "WBC",
    "TOTAL LEUKOCYTES":                      "WBC",

    # ── RBC ──
    "RED BLOOD CELL COUNT":                  "RBC",
    "RBC":                                   "RBC",
    "RBC COUNT":                             "RBC",
    "ERYTHROCYTE COUNT":                     "RBC",
    "RED CELL COUNT":                        "RBC",

    # ── Platelet ──
    "PLATELET COUNT":                        "PLATELET_COUNT",
    "PLATELETS":                             "PLATELET_COUNT",
    "PLT":                                   "PLATELET_COUNT",
    "PLATELET COUNT (PLT)":                  "PLATELET_COUNT",
    "THROMBOCYTE COUNT":                     "PLATELET_COUNT",
    "THROMBOCYTES":                          "PLATELET_COUNT",

    # ── Differential Counts ──
    "NEUTROPHILS":                           "NEUTROPHILS",
    "NEUTROPHIL":                            "NEUTROPHILS",
    "SEGMENTED NEUTROPHILS":                 "NEUTROPHILS",
    "POLY":                                  "NEUTROPHILS",
    "POLYMORPHS":                            "NEUTROPHILS",
    "LYMPHOCYTES":                           "LYMPHOCYTES",
    "LYMPHOCYTE":                            "LYMPHOCYTES",
    "EOSINOPHILS":                           "EOSINOPHILS",
    "EOSINOPHIL":                            "EOSINOPHILS",
    "MONOCYTES":                             "MONOCYTES",
    "MONOCYTE":                              "MONOCYTES",
    "BASOPHILS":                             "BASOPHILS",
    "BASOPHIL":                              "BASOPHILS",

    # ── CBC Indices ──
    "MCV":                                   "MCV",
    "MEAN CORPUSCULAR VOLUME":               "MCV",
    "MCH":                                   "MCH",
    "MEAN CORPUSCULAR HAEMOGLOBIN":          "MCH",
    "MCHC":                                  "MCHC",
    "MEAN CORPUSCULAR HAEMOGLOBIN CONCENTRATION": "MCHC",
    "PCV":                                   "PCV",
    "HAEMATOCRIT":                           "PCV",
    "HEMATOCRIT":                            "PCV",
    "PACKED CELL VOLUME":                    "PCV",
    "PACKED CELL VOLUME (PCV)":              "PCV",
    "HCT":                                   "PCV",
    "RDW":                                   "RDW",
    "RDW-CV":                                "RDW",
    "RED CELL DISTRIBUTION WIDTH":           "RDW",
    "MPV":                                   "MPV",
    "MEAN PLATELET VOLUME":                  "MPV",

    # ── LFT ──
    "ALANINE AMINOTRANSFERASE":              "ALT",
    "ALANINE AMINOTRANSFERASE (ALT/SGPT)":   "ALT",
    "ALANINE TRANSAMINASE":                  "ALT",
    "SGPT":                                  "ALT",
    "ALT":                                   "ALT",
    "ALT/SGPT":                              "ALT",
    "ASPARTATE AMINOTRANSFERASE":            "AST",
    "ASPARTATE AMINOTRANSFERASE (AST/SGOT)": "AST",
    "ASPARTATE TRANSAMINASE":                "AST",
    "SGOT":                                  "AST",
    "AST":                                   "AST",
    "AST/SGOT":                              "AST",
    "ALKALINE PHOSPHATASE":                  "ALP",
    "ALKALINE PHOSPHATASE (ALP)":            "ALP",
    "ALP":                                   "ALP",
    "SERUM BILIRUBIN":                       "BILIRUBIN_TOTAL",
    "TOTAL BILIRUBIN":                       "BILIRUBIN_TOTAL",
    "BILIRUBIN TOTAL":                       "BILIRUBIN_TOTAL",
    "BILIRUBIN - TOTAL":                     "BILIRUBIN_TOTAL",
    "T.BILIRUBIN":                           "BILIRUBIN_TOTAL",
    "DIRECT BILIRUBIN":                      "BILIRUBIN_DIRECT",
    "BILIRUBIN DIRECT":                      "BILIRUBIN_DIRECT",
    "CONJUGATED BILIRUBIN":                  "BILIRUBIN_DIRECT",
    "INDIRECT BILIRUBIN":                    "BILIRUBIN_INDIRECT",
    "BILIRUBIN INDIRECT":                    "BILIRUBIN_INDIRECT",
    "UNCONJUGATED BILIRUBIN":                "BILIRUBIN_INDIRECT",
    "ALBUMIN":                               "ALBUMIN",
    "SERUM ALBUMIN":                         "ALBUMIN",
    "GLOBULIN":                              "GLOBULIN",
    "TOTAL PROTEIN":                         "TOTAL_PROTEIN",
    "PROTEIN TOTAL":                         "TOTAL_PROTEIN",
    "GGT":                                   "GGT",
    "GAMMA GT":                              "GGT",
    "GAMMA-GLUTAMYL TRANSFERASE":            "GGT",
    "AST (SGOT) / ALT (SGPT) RATIO (DE RITIS)": "AST_ALT_RATIO",
    "AST (SGOT) / ALT (SGPT) RATIO (DERITIS)":  "AST_ALT_RATIO",

    # ── Kidney / RFT ──
    "SERUM CREATININE":                      "CREATININE",
    "CREATININE":                            "CREATININE",
    "SR CREATININE":                         "CREATININE",
    "BLOOD UREA":                            "UREA",
    "UREA":                                  "UREA",
    "BUN":                                   "BLOOD_UREA_NITROGEN",
    "BLOOD UREA NITROGEN":                   "BLOOD_UREA_NITROGEN",
    "URIC ACID":                             "URIC_ACID",
    "SERUM URIC ACID":                       "URIC_ACID",
    "EGFR":                                  "EGFR",
    "ESTIMATED GFR":                         "EGFR",

    # ── Electrolytes ──
    "SODIUM":                                "SODIUM",
    "SERUM SODIUM":                          "SODIUM",
    "NA":                                    "SODIUM",
    "NA+":                                   "SODIUM",
    "POTASSIUM":                             "POTASSIUM",
    "SERUM POTASSIUM":                       "POTASSIUM",
    "K":                                     "POTASSIUM",
    "K+":                                    "POTASSIUM",
    "CHLORIDE":                              "CHLORIDE",
    "SERUM CHLORIDE":                        "CHLORIDE",
    "CL":                                    "CHLORIDE",
    "BICARBONATE":                           "BICARBONATE",
    "CO2":                                   "BICARBONATE",
    "CALCIUM":                               "CALCIUM",
    "SERUM CALCIUM":                         "CALCIUM",
    "CA":                                    "CALCIUM",
    "PHOSPHORUS":                            "PHOSPHORUS",
    "SERUM PHOSPHORUS":                      "PHOSPHORUS",

    # ── Blood Glucose ──
    "RANDOM BLOOD SUGAR":                    "RBS",
    "RBS":                                   "RBS",
    "RANDOM BLOOD GLUCOSE":                  "RBS",
    "FASTING BLOOD SUGAR":                   "FBS",
    "FBS":                                   "FBS",
    "FASTING BLOOD GLUCOSE":                 "FBS",
    "POSTPRANDIAL BLOOD SUGAR":              "PPBS",
    "PPBS":                                  "PPBS",
    "HBA1C":                                 "HBA1C",
    "GLYCATED HAEMOGLOBIN":                  "HBA1C",
    "GLYCOSYLATED HEMOGLOBIN":               "HBA1C",
    "HAEMOGLOBIN A1C":                       "HBA1C",

    # ── Thyroid ──
    "TSH":                                   "TSH",
    "THYROID STIMULATING HORMONE":           "TSH",
    "T3":                                    "T3",
    "TRIIODOTHYRONINE":                      "T3",
    "T4":                                    "T4",
    "THYROXINE":                             "T4",
    "FREE T3":                               "FREE_T3",
    "FT3":                                   "FREE_T3",
    "FREE T4":                               "FREE_T4",
    "FT4":                                   "FREE_T4",

    # ── Lipid Profile ──
    "TOTAL CHOLESTEROL":                     "CHOLESTEROL_TOTAL",
    "CHOLESTEROL":                           "CHOLESTEROL_TOTAL",
    "CHOLESTEROL TOTAL":                     "CHOLESTEROL_TOTAL",
    "HDL CHOLESTEROL":                       "HDL",
    "HDL":                                   "HDL",
    "HDL-C":                                 "HDL",
    "LDL CHOLESTEROL":                       "LDL",
    "LDL":                                   "LDL",
    "LDL-C":                                 "LDL",
    "VLDL":                                  "VLDL",
    "TRIGLYCERIDES":                         "TRIGLYCERIDES",
    "TRIGLYCERIDE":                          "TRIGLYCERIDES",
    "TG":                                    "TRIGLYCERIDES",

    # ── Vitals (from discharge summaries) ──
    "TEMPERATURE":                           "TEMPERATURE",
    "TEMP":                                  "TEMPERATURE",
    "PULSE":                                 "PULSE",
    "HEART RATE":                            "PULSE",
    "BP":                                    "BLOOD_PRESSURE",
    "BLOOD PRESSURE":                        "BLOOD_PRESSURE",
    "SPO2":                                  "SPO2",
    "OXYGEN SATURATION":                     "SPO2",
    "RESPIRATORY RATE":                      "RESPIRATORY_RATE",
    "RR":                                    "RESPIRATORY_RATE",

    # ── Others ──
    "CRP":                                   "CRP",
    "C-REACTIVE PROTEIN":                    "CRP",
    "ESR":                                   "ESR",
    "ERYTHROCYTE SEDIMENTATION RATE":        "ESR",
    "FERRITIN":                              "FERRITIN",
    "SERUM FERRITIN":                        "FERRITIN",
    "VITAMIN B12":                           "VITAMIN_B12",
    "VIT B12":                               "VITAMIN_B12",
    "VITAMIN D":                             "VITAMIN_D",
    "VIT D":                                 "VITAMIN_D",
    "25-OH VITAMIN D":                       "VITAMIN_D",
    "PROTHROMBIN TIME":                      "PT",
    "PT":                                    "PT",
    "INR":                                   "INR",
    "PT INR":                                "INR",
    "APTT":                                  "APTT",
    "ACTIVATED PARTIAL THROMBOPLASTIN TIME": "APTT",
    "D-DIMER":                               "D_DIMER",
    "DENGUE NS1":                            "DENGUE_NS1",
    "DENGUE IGM":                            "DENGUE_IGM",
    "DENGUE IGG":                            "DENGUE_IGG",
    "MALARIA":                               "MALARIA",
    "COVID-19":                              "COVID19",
    "SARS-COV-2":                            "COVID19",
    "WIDAL":                                 "WIDAL",
    "WIDAL TEST":                            "WIDAL",
    "WIDAL TEST (SLIDE METHOD)":             "WIDAL",
    "SALMONELLA TYPHI O`":                   "WIDAL_TYPHI_O",
    "SALMONELLA TYPHI H":                    "WIDAL_TYPHI_H",
    "SALMONELLA TYPHI O` , SERUM":           "WIDAL_TYPHI_O",
    "SALMONELLA TYPHI 'H' , SERUM":          "WIDAL_TYPHI_H",

    # ── Urine Analysis ──
    "PH":                                    "URINE_PH",
    "SP. GRAVITY":                           "URINE_SPECIFIC_GRAVITY",
    "SPECIFIC GRAVITY":                      "URINE_SPECIFIC_GRAVITY",
    "URINE PH":                              "URINE_PH",
    "URINE SPECIFIC GRAVITY":                "URINE_SPECIFIC_GRAVITY",
    "URINE GLUCOSE":                         "URINE_GLUCOSE",
    "GLUCOSE":                               "URINE_GLUCOSE",
    "URINE PROTEIN":                         "URINE_PROTEIN",
    "PROTEIN (ALBUMIN)":                     "URINE_PROTEIN",
    "URINE BILIRUBIN":                       "URINE_BILIRUBIN",
    "BILIRUBIN":                             "URINE_BILIRUBIN",
    "URINE KETONES":                         "URINE_KETONES",
    "URINE KETONES (RANDOM)":                "URINE_KETONES",
    "KETONE BODIES":                         "URINE_KETONES",
    "NITRITE":                               "URINE_NITRITE",
    "UROBILINOGEN":                          "URINE_UROBILINOGEN",
    "LEUCOCYTE ESTERASE":                    "URINE_LEUCOCYTE_ESTERASE",
    "BLOOD":                                 "URINE_BLOOD",
    "VOLUME":                                "URINE_VOLUME",
    "COLOUR":                                "URINE_COLOUR",
    "TRANSPARENCY":                          "URINE_TRANSPARENCY",
    "TRANSPARENCY (APPEARANCE)":             "URINE_TRANSPARENCY",
    "PUS CELLS":                             "URINE_PUS_CELLS",
    "PUS CELLS(LIGHT MICROSCOPY)/HPF":       "URINE_PUS_CELLS",
    "RED BLOOD CELLS":                       "URINE_RBC",
    "RED BLOOD CELLS(LIGHT MICROSCOPY)":     "URINE_RBC",
    "EPITHELIAL CELLS":                      "URINE_EPITHELIAL_CELLS",
    "EPITHELIAL CELLS(LIGHT MICROSCOPY)":    "URINE_EPITHELIAL_CELLS",
    "CASTS":                                 "URINE_CASTS",
    "CASTS(LIGHT MICROSCOPY)":               "URINE_CASTS",
    "CRYSTALS":                              "URINE_CRYSTALS",
    "CRYSTALS(LIGHT MICROSCOPY)":            "URINE_CRYSTALS",
    "OTHERS(LIGHT MICROSCOPY":               "URINE_OTHERS",

    # ── ABG (Arterial Blood Gas) ──
    "PH (ABG)":                              "ABG_PH",
    "PCO2":                                  "ABG_PCO2",
    "PO2":                                   "ABG_PO2",
    "HCO3":                                  "ABG_HCO3",
    "BE":                                    "ABG_BASE_EXCESS",
    "BASE EXCESS":                           "ABG_BASE_EXCESS",
    "SAO2":                                  "ABG_SAO2",
    "FIO2":                                  "ABG_FIO2",

    # ── Pancreatic ──
    "LIPASE":                                "LIPASE",
    "LIPASE,SERUM":                          "LIPASE",
    "SERUM LIPASE":                          "LIPASE",
    "AMYLASE":                               "AMYLASE",
    "SERUM AMYLASE":                         "AMYLASE",

    # ── Proteins / Immunology ──
    "ALBUMIN/GLOBULIN RATIO":                "AG_RATIO",
    "A/G RATIO":                             "AG_RATIO",
    "SERUM BILIRUBIN (TOTAL, DIRECT & INDIRECT)": "BILIRUBIN_TOTAL",
    "GGT (GAMMA GLUTAMYL TRANSPEPTIDASE)":   "GGT",
    "GAMMA GLUTAMYL TRANSPEPTIDASE":         "GGT",
    "ASPARTATE TRANSAMINASE (SGOT, HAST)":   "AST",
    "MEAN CELL VOLUME (MCV)":                "MCV",
    "RDW - CV":                              "RDW",
    "RDW-CV":                                "RDW",
    "DIFFERENTIAL LEUKOCYTE COUNTS":         "DIFFERENTIAL_COUNT",
    "DIFFERENTIAL LEUKOCYTE COUNT":          "DIFFERENTIAL_COUNT",
    "DIFFERENTIAL COUNT":                    "DIFFERENTIAL_COUNT",
    "DIFFERENTIAL LEUKOCYTIC COUNT (DLC)":   "DIFFERENTIAL_COUNT",
    "R.D.W":                                 "RDW",
    "RDW - SD":                              "RDW_SD",
    "RDW-SD":                                "RDW_SD",
    "CORRECTED TLC":                         "WBC_CORRECTED",
    "ABSOLUTE LEUCOCYTE COUNT":              "WBC_ABSOLUTE",
    "NEUTROPHIL LYMPHOCYTE RATIO (NLR)":     "NLR",
    "PERIPHERAL SMEAR FOR MALARIAL PARASITE (MP)": "MALARIA_SMEAR",
    "MALARIA VIVAX ANTIGEN":                 "MALARIA_VIVAX",
    "MALARIA FALCIPARUM ANTIGEN":            "MALARIA_FALCIPARUM",
    "BILIRUBIN CONJUGATED(DIRECT)":          "BILIRUBIN_DIRECT",
    "BILIRUBIN CONJUGATED (DIRECT)":         "BILIRUBIN_DIRECT",
    "AST(SGOT)/ALT(SGPT)RATIO(DERITIS)":     "AST_ALT_RATIO",
    "EGFR - ESTIMATED GLOMERULAR":           "EGFR",
    "FILTRATION RATE":                       "EGFR",
    "PHOSPHORUS, INORGANIC":                 "PHOSPHORUS",
    "S.PARATYPHI A 'H'":                     "PARATYPHI_A_H",
    "S.PARATYPHI B 'H'":                     "PARATYPHI_B_H",
    "S.PARATYPHI A 'H' , SERUM":             "PARATYPHI_A_H",
    "S.PARATYPHI B 'H' , SERUM":             "PARATYPHI_B_H",
    "TYPHIDOT IGG AND IGM":                  "TYPHIDOT",
    "TYPHIDOT IGG AND IGM, SERUM":           "TYPHIDOT",
    "TYPHIDOT IGG AND IGM , SERUM":          "TYPHIDOT",
    "CULTURE AND SENSITIVITY - AEROBIC (BLOOD)": "BLOOD_CULTURE",
    "SODIUM (NA+)":                          "SODIUM",
    "POTASSIUM (K+)":                        "POTASSIUM",
    "CHLORIDE (CI-)":                        "CHLORIDE",
    "CHLORIDE (CL-)":                        "CHLORIDE",
    "URINE R/M":                             "URINE_ROUTINE_MICROSCOPIC",
}

# ─── UNIT CANONICAL REGISTRY ───────────────────────────────────────────────────
# Keys  : raw unit strings (UPPERCASE)
# Values: canonical SI/medical unit

UNIT_MAPPING: dict[str, str] = {
    "G/DL":              "g/dL",
    "G%":                "g/dL",
    "GM/DL":             "g/dL",
    "GMS/DL":            "g/dL",
    "G/100ML":           "g/dL",
    "GM%":               "g/dL",
    "MG/DL":             "mg/dL",
    "MG%":               "mg/dL",
    "MG/100ML":          "mg/dL",
    "UG/DL":             "µg/dL",
    "MCG/DL":            "µg/dL",
    "NG/ML":             "ng/mL",
    "NG/DL":             "ng/dL",
    "PG/ML":             "pg/mL",
    "PMOL/L":            "pmol/L",
    "NMOL/L":            "nmol/L",
    "UMOL/L":            "µmol/L",
    "MMOL/L":            "mmol/L",
    "MEQ/L":             "mEq/L",
    "MEQ":               "mEq/L",
    "U/L":               "U/L",
    "IU/L":              "U/L",
    "MU/L":              "mU/L",
    "UIU/ML":            "µIU/mL",
    "MIU/ML":            "mIU/mL",
    "MILLI IU/ML":       "mIU/mL",
    "MICRO IU/ML":       "µIU/mL",
    "CELLS/CMM":         "cells/mcL",
    "CELLS/CU.MM":       "cells/mcL",
    "CELLS/CUMM":        "cells/mcL",
    "CELLS/MCL":         "cells/mcL",
    "/CMM":              "/mcL",
    "/CU.MM":            "/mcL",
    "/CUMM":             "/mcL",
    "CMM":               "cells/mcL",
    "CU.MM":             "cells/mcL",
    "CUMM":              "cells/mcL",
    "MILLION/CMM":       "million/mcL",
    "MILL/CMM":          "million/mcL",
    "MILLION/CU.MM":     "million/mcL",
    "MILLIONS/CUMM":     "million/mcL",
    "10^6/UL":           "million/mcL",
    "X10^6/UL":          "million/mcL",
    "10^3/UL":           "10³/mcL",
    "THOU/UL":           "10³/mcL",
    "K/UL":              "10³/mcL",
    "X10^3/UL":          "10³/mcL",
    "FL":                "fL",
    "PG":                "pg",
    "%":                 "%",
    "PERCENT":           "%",
    "MMHG":              "mmHg",
    "MM HG":             "mmHg",
    "MM OF HG":          "mmHg",
    "SEC":               "seconds",
    "SECONDS":           "seconds",
    "MM/HR":             "mm/hr",
    "MM/HOUR":           "mm/hr",
    "BPM":               "bpm",
    "/MIN":              "/min",
    "MIN":               "min",
    "DEGREE F":          "°F",
    "°F":                "°F",
    "DEGREE C":          "°C",
    "°C":                "°C",
}

# ─── IGNORE LIST ──────────────────────────────────────────────────────────────
# Test names that are headers, panel labels, or non-quantifiable entries

IGNORE_TESTS = {
    "TEST_NAME", "RANGE", "RESULT", "UNIT",
    "CBC (COMPLETE BLOOD COUNT)* (SPECIMEN : EDTA)",
    "COMPLETE BLOOD COUNT (CBC) , WHOLE BLOOD EDTA",
    "COMPLETE BLOOD COUNT (CBC)",
    "LFT (LIVER FUNCTION TEST)", "LIVER FUNCTION TEST(LFT)",
    "LIVER FUNCTION TEST (LFT) , SERUM", "LIVER FUNCTION TEST(LFT),SERUM",
    "RENAL PROFILE/KIDNEY FUNCTION TEST (RFT/KFT), SERUM",
    "COMPLETE URINE EXAMINATION (CUE)",
    "URINE ROUTINE AND MICROSCOPIC EXAMINATION",
    "BIOCHEMICAL EXAMINATION", "DIAGNOSTICS",
    "USG W/A", "USG WHOLE ABDOMEN", "ULTRASOUND WHOLE ABDOMEN",
    "COMMENT", "ABSENT", "NEGATIVE",
    "CENTRIFUGED SEDIMENT WET MOUNT AND MICROSCOPY",
    "FEVER", "VOMITING", "HEADACHE", "GENERALIZED WEAKNESS",
    "PAIN ABDOMEN", "REDUCED ORAL INTAKE", "DIET",
    "TOTAL INTAKE", "TOTAL OUTPUT", "WEIGHT",
    "CHEST", "CVS", "P/A", "RESP. RATE",
}
